# Bump version
name: Bump version
on:
  push:
    branches: [ 'master' ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Replace Version in README
        uses: datamonsters/replace-action@v2
        with:
          files:  'Readme.md'
          replacements:  "%%version%%=${{ steps.tag_version.outputs.new_version }}"
      - name: rSync to Production
        uses: burnett01/rsync-deployments@5.2.1
        with:
          switches: -avzr --delete
          path: web/
          remote_path: ~/www/webdevw30.sg-host.com/public_html/
          remote_host: ${{ secrets.DEPLOY_HOST }}
          remote_user: ${{ secrets.DEPLOY_USER }}
          remote_key: ${{ secrets.DEPLOY_KEY }}
      # - name: Sync to Production
      #   env:
      #     dest: '${{ secrets.DEPLOYMENT_SERVER_USERNAME }}@${{ secrets.DEPLOYMENT_SERVER_IP }}:~/www/webdevw30.sg-host.com/'
      #   run: |
      #     echo "${{secrets.SSH_PRIVATE_KEY}}" > deploy_key
      #     chmod 600 ./deploy_key
      #     rsync -zvr --delete \
      #       -e 'ssh -i ./deploy_key -o StrictHostKeyChecking=no -p 18765' \
      #       --include './web' \
      #       --exclude '*' \
      #       ./ ${{env.dest}}